config/routes.rb
Rails.application.routes.draw do
  # API routing
  scope module: 'api', defaults: {format: 'json'} do
    namespace :v1 do
      # Only need two routes for the API
      get 'orders', to: 'orders#index'
      get 'customers/:id', to: 'customers#show'
    end
  end

  # Semi-static page routes
  get 'home', to: 'home#index', as: :home
  get 'home/about', to: 'home#about', as: :about
  get 'home/contact', to: 'home#contact', as: :contact
  get 'home/privacy', to: 'home#privacy', as: :privacy
  # get 'home/search', to: 'home#search', as: :search
  get 'search', to: 'search#search', as: :search

  # Authentication routes
  get 'login', to: 'sessions#new', as: :login
  get 'logout', to: 'sessions#destroy', as: :logout
  
  resources :sessions, :only => [:new, :create, :destroy]
  resources :customers, :except => [:destroy]
  resources :addresses
  resources :categories, :except => [:show, :destroy]
  resources :items
  resources :orders
  resources :users, :except => [:show, :destroy]

  patch 'items/:id/toggle_active', to: 'items#toggle_active', as: :toggle_active
  patch 'items/:id/toggle_feature', to: 'items#toggle_feature', as: :toggle_feature
  get 'place_order', to: 'orders#create', as: :place_order

  get 'item_prices/new', to: 'item_prices#new', as: :new_item_price
  post 'item_prices/create', to: 'item_prices#create', as: :item_prices

  # URL, Method, Path
  get 'cart/view_cart', to: 'cart#show', as: :view_cart
  get 'cart/:id/add_item', to: 'cart#add_item', as: :add_item
  get 'cart/:id/remove_item', to: 'cart#remove_item', as: :remove_item
  get 'cart/empty_cart', to: 'cart#empty_cart', as: :empty_cart
  get 'cart/checkout', to: 'cart#checkout', as: :checkout

  root 'home#index'
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  include AppHelpers::Cart
  include AppHelpers::Shipping

  before_action :set_item, :only => [:add_item, :remove_item]

  def show
    @items_in_cart = get_list_of_items_in_cart()
    @subtotal = calculate_cart_items_cost()
    @shipping_cost = calculate_cart_shipping()
    @total = @subtotal + @shipping_cost
  end

  def add_item
    @item = Item.find(params[:id])
    add_item_to_cart(params[:id])
    redirect_to @item
    flash[:notice] = "#{@item.name} was added to cart."
  end

  def remove_item
    @item = Item.find(params[:id])
    remove_item_from_cart(params[:id])
    redirect_to view_cart_path
    flash[:notice] = "#{@item.name} was removed from cart."
  end

  def empty_cart
    clear_cart()
    redirect_to view_cart_path
    flash[:notice] = "Cart is emptied."
  end

  def checkout
    @items_in_cart = get_list_of_items_in_cart()
    @subtotal = calculate_cart_items_cost()
    @shipping_cost = calculate_cart_shipping()
    @total = @subtotal + @shipping_cost
    @addresses = current_user.customer.addresses.by_recipient
    @order = Order.new
    # redirect_to order_path(@order)
  end

  private
  def set_item
    @item = Item.find(params[:id])
  end

end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/cart/_cart_list.html.erb
<h4>Your Cart</h4>

<% if num_unique_items_in_cart == 0 %>
  <br /><h5>Your cart is currently empty.</h5><br />
<% else %>
  <% for ord_item in @items_in_cart %>
    <b>Name: </b>
      <%= ord_item.item.name %><br />
    
    <b>Unit Price: </b>
      <%= ord_item.item.item_prices.current.first.nil? ? 'N/A' : number_to_currency(ord_item.item.item_prices.current.first.price) %><br />

    <b>Quantity: </b>
      <%= ord_item.quantity %><br />

    <b>Subtotal: </b>
      <%= number_to_currency(ord_item.subtotal) %><br />

    <b><%= link_to "Remove", remove_item_path(ord_item.item) %></b>
    <br /><br />
  <% end %>

  <b><%= link_to "Empty cart", empty_cart_path %></b><br />
  <hr />

  <b>Subtotal: </b>
    <%= number_to_currency(@subtotal) %><br />
  
  <b>Shipping: </b>
    <%= number_to_currency(@shipping_cost) %><br />

  <b>Grand Total: </b>
    <%= number_to_currency(@total) %>
  
  <%# <table class="striped highlight"> %>
    <%# <thead> %>
      <%# <th>Name</th> %>
      <%# <th>Unit Price</th> %>
      <%# <th>Quantity</th> %>
      <%# <th class="align_center">Options</th> %>
    <%# </thead> %>
    
    <%# <% for ord_item in @items_in_cart %>
      <%# <tr> %>
        <%# <td><%= link_to ord_item.item.name, item_path(ord_item.item) </td> %>
        <%# <td class="align_center"><%= ord_item.item.item_prices.current.first.nil? ? 'N/A' : number_to_currency(ord_item.item.item_prices.current.first.price) </td> %>
        <%# <td class="align_center"><%= link_to "Add to Cart", add_item_path(ord_item.item) %>
        <%# <td><%= ord_item.quantity </td> %>
        <%# <td class="align_center"> %>
        <%# <%= link_to remove_item_path(ord_item.item) do %>
            <%# &nbsp;&nbsp; %>
            <%# <i class="material-icons">delete</i> %>
        <%# <% end %>
        <%# </td> %>
      <%# </tr> %>
    <%# <% end %>
  <%# </table> %>
  <br /><br />
  
<% end %>

<%= render :partial => "partials/add_new_object", locals: {model_name: 'item'} %>
<%= render :partial => "partials/cart_options", locals: {model_name: 'item'} %>

app/views/cart/_order_fields.html.erb
<%= f.input :customer_id, as: :hidden, input_html: { value: current_user.customer.id } %>
<%= f.input :address_id, collection: get_address_options_long(current_user), include_blank: true %>
<%= link_to "Add a new address", new_address_path %>
<%= f.input :credit_card_number, input_html: { class: 'active' } %>
<%= f.input :expiration_month, collection: (1..12).to_a %>
<%= f.input :expiration_year, collection: get_credit_expiration_year(Date.current) %>
<%= f.input :total, as: :hidden, input_html: { value: @total } %>

app/views/cart/checkout.html.erb
<div class="row">
  <div class="col s9">
    <div class="card">    
      <div class="card-content">
        <span class="card-title"><%= "New Order" %></span>
        <%= simple_form_for(@order) do |f| %>
          <%= f.error_notification %>
          <div class="row">
            <div class="form-inputs">
              <%= render partial: "order_fields", locals: { f: f } %>
            </div>
          </div>
          <p>&nbsp;</p>
          <div class="row">
            <div class="form-actions col s9">
              <%= f.button :submit, 'Place order', class: 'btn btn-primary' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<%= link_to 'Back', :back %>

app/views/cart/show.html.erb
<%= render partial: "partials/structure1", locals: {model_name: "cart", 
                                                       primary: "cart_list", 
                                                       secondary: nil,
                                                       sidebar: nil } %>