config/routes.rb
Rails.application.routes.draw do
  # API routing
  scope module: 'api', defaults: {format: 'json'} do
    namespace :v1 do
      # Only need two routes for the API
      get 'orders', to: 'orders#index'
      get 'customers/:id', to: 'customers#show'
    end
  end

  # Semi-static page routes
  get 'home', to: 'home#index', as: :home
  get 'home/about', to: 'home#about', as: :about
  get 'home/contact', to: 'home#contact', as: :contact
  get 'home/privacy', to: 'home#privacy', as: :privacy
  # get 'home/search', to: 'home#search', as: :search
  get 'search', to: 'search#search', as: :search

  # Authentication routes
  get 'login', to: 'sessions#new', as: :login
  get 'logout', to: 'sessions#destroy', as: :logout
  
  resources :sessions, :only => [:new, :create, :destroy]
  resources :customers, :except => [:destroy]
  resources :addresses
  resources :categories, :except => [:show, :destroy]
  resources :items
  resources :orders
  resources :users, :except => [:show, :destroy]

  patch 'items/:id/toggle_active', to: 'items#toggle_active', as: :toggle_active
  patch 'items/:id/toggle_feature', to: 'items#toggle_feature', as: :toggle_feature
  get 'place_order', to: 'orders#create', as: :place_order

  get 'item_prices/new', to: 'item_prices#new', as: :new_item_price
  post 'item_prices/create', to: 'item_prices#create', as: :item_prices

  # URL, Method, Path
  get 'cart/view_cart', to: 'cart#show', as: :view_cart
  get 'cart/:id/add_item', to: 'cart#add_item', as: :add_item
  get 'cart/:id/remove_item', to: 'cart#remove_item', as: :remove_item
  get 'cart/empty_cart', to: 'cart#empty_cart', as: :empty_cart
  get 'cart/checkout', to: 'cart#checkout', as: :checkout

  root 'home#index'
end

app/views/partials/_add_new_object.html.erb
<!-- Add a button for new instances of object -->
<% if can? :new, eval(model_name.capitalize) && controller.respond_to?(:new) %>
  <%= link_to(eval("new_#{model_name}_path"), class: "waves-effect waves-light btn") do %>
    &nbsp;Add a New <%= model_name.capitalize %>
  <% end %>
<% end %>

app/views/partials/_cart_options.html.erb
<% if can? :index, Item %>
  <% if num_unique_items_in_cart == 0 %>
    <%= link_to(eval("items_path"), class: 'waves-effect waves-light btn') do %>
      <%= "Start shopping" %>
    <% end %>
  <% else %>
    <%= link_to(eval("items_path"), class: 'waves-effect waves-light btn') do %>
      <%= "Continue shopping" %>
    <% end %>
  <% end %>
<% end %>

<% if can? :checkout, Order %>
  <% if num_unique_items_in_cart > 0 %>
    <%= link_to(eval("checkout_path"), class: 'waves-effect waves-light btn') do %>
      <%= "Checkout" %>
    <% end %>
  <% end %>
<% end %>

app/views/partials/_flash.html.erb
<% flash.each do |name, msg| %>
  <div data-alert data-options="animation_speed:500, animation:'fadeOut';" class="alert-box <%= flash[:notice] ? "success" : "warning" %>">
    <!-- <a href="#" class="close">&times;</a> -->
    <%= msg %>
  </div>
<% end %>

app/views/partials/_footer.html.erb
<p class="supertiny">&nbsp;</p>

<div id="footer" class="center-align">
  
  <%= link_to 'Home', home_path %>&nbsp;&nbsp;::&nbsp;&nbsp;
  <%= link_to 'About', about_path %>&nbsp;&nbsp;::&nbsp;&nbsp;
  <%= link_to 'Contact', contact_path %>&nbsp;&nbsp;::&nbsp;&nbsp;
  <%= link_to 'Privacy Policy', privacy_path %>
  <br/>
  <div id="copy">
    Webmaster: <%= mail_to("stevenz2@andrew.cmu.edu", "Steven Zhang", encode: "javascript") %> 
    &nbsp;&nbsp;&copy 2022
  </div>

</div>

app/views/partials/_form2_structure.html.erb
<%# FOR NESTED FORMS; 2 SETS OF FIELDS %>
<div class="row">
  <div class="col s9">
    <div class="card">    
      <div class="card-content">
        <span class="card-title"><%= type_of_form %></span>
        <%= simple_form_for(object) do |f| %>
          <%= f.error_notification %>
          <div class="row">
            <div class="form-inputs">
              <%# First set of fields for main object %>
              <%= render partial: "#{fields1}", locals: { f: f } %>
            </div>
          </div>
          <div class="row">
            <div class="col s12">
              <div class="card grey lighten-3">
                <div class="row">
                  <div class="card-content">
                    <%# Second set of fields and title for nested object %>
                    <span class="card-title"><%= section_2 %></span>
                    <div class="form-inputs">
                      <%= render partial: "#{fields2}", locals: { f: f } %>
                    </div>
                  </div>
                </div>    
              </div>              
            </div>
          </div>
          <p>&nbsp;</p>
          <div class="row">
            <div class="form-actions col s9">
              <%= f.button :submit %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<%= link_to 'Back', :back %>

app/views/partials/_form_structure.html.erb
<div class="row">
  <div class="col s9">
    <div class="card">    
      <div class="card-content">
        <span class="card-title"><%= type_of_form %></span>
        <%= simple_form_for(object) do |f| %>
          <%= f.error_notification %>
          <div class="row">
            <div class="form-inputs">
              <%= render partial: "#{fields}", locals: { f: f } %>
            </div>
          </div>
          <p>&nbsp;</p>
          <div class="row">
            <div class="form-actions col s9">
              <%= f.button :submit %> <!-- Turns into Create xxx -->
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<%= link_to 'Back', :back %>

app/views/partials/_nav_admin.html.erb
<nav id="nav">
  <div class="container">
    <ul class="left hide-on-med-and-down">
      <li><%= link_to 'Customers', customers_path %></li>
      <li><%= link_to 'Items', items_path %></li>
      <li><%= link_to 'Orders', orders_path %></li>
      <li><%= link_to 'Employees', users_path %></li>

    </ul>
    <ul class="right">
      <li><%= link_to 'Logout', logout_path %></li>
    </ul>
  </div>
</nav>

app/views/partials/_nav_customer.html.erb
<nav id="nav">
  <div class="container">
    <ul class="left hide-on-med-and-down">
      <li><%= link_to 'Items', items_path %></li>
      <% if num_unique_items_in_cart == 0 %>
        <li><%= link_to "View Cart", view_cart_path %>
      <% else %>
        <li><%= link_to "View Cart(#{num_unique_items_in_cart})", view_cart_path %>
      <% end %>
      <li><%= link_to 'My Account', customer_path(current_user.customer) %>
      <li><%= link_to 'My Orders', orders_path %>
    
    </ul>
    <ul class="right">
      <li><%= link_to 'Logout', logout_path %></li>
    </ul>
  </div>
</nav>

app/views/partials/_nav_guest.html.erb
<nav id="nav">
  <div class="container">
    <ul class="right">
      <li><%= link_to "Become a Customer", new_customer_path %></li>&nbsp;
      <li><%= link_to "Login", login_path %></li>
      <li><%= link_to 'Items', items_path %></li>
    </ul>
  </div>
</nav>

app/views/partials/_object_options.html.erb
<% opt = "#{object.respond_to?(:name) ? object.name : model_name.capitalize }" %>

<div class="form-actions">
  <% if can? :index, eval(model_name.capitalize) %>
    <%= link_to(eval("#{model_name.pluralize}_path"), class: 'waves-effect waves-light btn') do %>
      &nbsp;Display All <%# model_name.pluralize.capitalize %>
    <% end %>
    &nbsp;&nbsp;
  <% end %>
  
  <% if can? :edit, object %>
    <%= link_to(eval("edit_#{model_name}_path(object)"), class: 'waves-effect waves-light btn') do %>
        &nbsp;<%= "Edit #{opt}" %>
    <% end %>
    &nbsp;&nbsp;
  <% end %>
  
  <% if can?(:destroy, object) && controller.respond_to?(:destroy) %>
    <%= link_to(eval("#{model_name}_path(object)"), method: 'delete', data: {confirm: "Are you sure you want to permanently delete #{opt}"}, class: 'waves-effect waves-light btn btn-alert') do %>
        &nbsp;<%= "Delete #{opt}" %>
    <% end %>
  <% end %>

  <br /><br />

  <% if can? :toggle_active, object %>
    <% if object.class == Item || object.class == Customer %>
      <%= link_to(eval("toggle_active_path"), method: 'patch', class: 'waves-effect waves-light btn') do %>
          <% if object.active? %>
            <%= "Make Inactive" %>
          <% else %>
            <%= "Make Active" %>
          <% end %>
      <% end %>
      &nbsp;&nbsp;
    <% end %>
  <% end %>

  <% if can? :toggle_featured, object %>
    <% if object.class == Item %>
      <%= link_to(eval("toggle_feature_path"), method: 'patch', class: 'waves-effect waves-light btn') do %>
          <% if object.is_featured? %>
            <%= "Stop Featured" %>
          <% else %>
            <%= "Make Featured" %>
          <% end %>
      <% end %>
      &nbsp;&nbsp;
    <% end %>
  <% end %>

  <% if can? :add_to_cart, Order %>
    <% if object.class == Item %>
      <%= link_to(eval("add_item_path(object)"), class: 'waves-effect waves-light btn') do %>
        <%= "Add to Cart" %>
      <% end %>
    <% end %>
  <% end %>

</div>

app/views/partials/_search_form.html.erb
<%= form_with url: search_path, method: :get, class: "form-inline", id: "search" do %>
    <%= text_field_tag 'query', '', placeholder: "Search ..." %>
    <!-- submitting via js (press enter) so not using... -->
    <%# submit_tag('Find') %>
  
<% end %>

app/views/partials/_show_structure.html.erb
<div class="row">
  <div class="col s7">
    <!-- primary partial gets displayed here in main div -->
    <%= render partial: "#{primary}" %>
    <!-- sometimes we want another partial below -->
    <% unless secondary.nil? %>
      <p>&nbsp;</p>
      <%= render partial: "#{secondary}" %>
    <% end %>
  </div>
  <div class="col s1">
    <!-- add a spacing column -->
    <p>&nbsp;</p>
  </div>
  <div class="col s4">
    <!-- render the sidebar, if it exists -->
    <%= render partial: "#{sidebar}" unless sidebar.blank? %>
  </div>
</div>
<!-- Add base errors and/or buttons for object management -->
<div class="row">
  <%= render :partial => "partials/display_base_errors", locals: {object: object} %>
  <%= render :partial => "partials/object_options", locals: {model_name: model_name, object: object} %>
</div>

app/views/partials/_topbar.html.erb
<div class="row valign-wrapper" id="topbar">
  <div class="col s1">
    <%= link_to(image_tag('rotated_cupcake_80x115.png'), home_path) %>
  </div>
  <div class="col s8">
    <h2>The Great Pittsburgh Baking Outlet</h2>
  </div>
  <div class="col s2">
    <%= render partial: 'partials/search_form' %>
  </div>
  <div class="col s1">
    &nbsp;
  </div>
</div>