config/routes.rb
Rails.application.routes.draw do
  # API routing
  scope module: 'api', defaults: {format: 'json'} do
    namespace :v1 do
      # Only need two routes for the API
      get 'orders', to: 'orders#index'
      get 'customers/:id', to: 'customers#show'
    end
  end

  # Semi-static page routes
  get 'home', to: 'home#index', as: :home
  get 'home/about', to: 'home#about', as: :about
  get 'home/contact', to: 'home#contact', as: :contact
  get 'home/privacy', to: 'home#privacy', as: :privacy
  # get 'home/search', to: 'home#search', as: :search
  get 'search', to: 'search#search', as: :search

  # Authentication routes
  get 'login', to: 'sessions#new', as: :login
  get 'logout', to: 'sessions#destroy', as: :logout
  
  resources :sessions, :only => [:new, :create, :destroy]
  resources :customers, :except => [:destroy]
  resources :addresses
  resources :categories, :except => [:show, :destroy]
  resources :items
  resources :orders
  resources :users, :except => [:show, :destroy]

  patch 'items/:id/toggle_active', to: 'items#toggle_active', as: :toggle_active
  patch 'items/:id/toggle_feature', to: 'items#toggle_feature', as: :toggle_feature
  get 'place_order', to: 'orders#create', as: :place_order

  get 'item_prices/new', to: 'item_prices#new', as: :new_item_price
  post 'item_prices/create', to: 'item_prices#create', as: :item_prices

  # URL, Method, Path
  get 'cart/view_cart', to: 'cart#show', as: :view_cart
  get 'cart/:id/add_item', to: 'cart#add_item', as: :add_item
  get 'cart/:id/remove_item', to: 'cart#remove_item', as: :remove_item
  get 'cart/empty_cart', to: 'cart#empty_cart', as: :empty_cart
  get 'cart/checkout', to: 'cart#checkout', as: :checkout

  root 'home#index'
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Modules to help with some functionality
  include AppHelpers::Validations
  include AppHelpers::Deletions
  include AppHelpers::Activeable::InstanceMethods
  extend AppHelpers::Activeable::ClassMethods

  attr_accessor :username, :password, :password_confirmation, :role, :greeting

  # Relationships
  belongs_to :user
  has_many :addresses
  has_many :orders
  has_many :order_items, through: :orders

  # Scopes
  scope :alphabetical,  -> { order(:last_name, :first_name) }
  scope :search,        ->(term) { where('first_name LIKE ? OR last_name LIKE ?', "%#{term}%", "#{term}%") }


  # Validations
  validates_presence_of :first_name, :last_name
  validates_format_of :phone, with: /\A(\d{10}|\(?\d{3}\)?[-. ]\d{3}[-.]\d{4})\z/, message: "should be 10 digits (area code needed) and delimited with dashes only"
  validates_format_of :email, with: /\A[\w]([^@\s,;]+)@(([\w-]+\.)+(com|edu|org|net|gov|mil|biz|info))\z/i, message: "is not a valid format"

  # Callbacks
  before_save    -> { strip_nondigits_from(:phone) }
  before_update :deactive_user_if_customer_inactive
  before_destroy :cannot_destroy_object

  # Other methods
  def name 
    "#{last_name}, #{first_name}"
  end

  def proper_name
    "#{first_name} #{last_name}"
  end

  def billing_address
    self.addresses.active.billing.first
  end

  private  
  def deactive_user_if_customer_inactive
    if !self.active && !self.user.nil?
      self.user.active = false
      self.user.save
    end
  end

end

app/controllers/api/v1/customers_controller.rb
module Api::V1
  class CustomersController < ApiController
    def show 
      @customer = Customer.find(params[:id])
      render json: CustomerSerializer.new(@customer).serialized_json
    end
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  include AppHelpers::Cart

  before_action :set_customer, :only => [:show, :edit, :update]
  before_action :check_login, :only => [:show, :update, :edit]
  authorize_resource

  def index
    @active_customers = Customer.active.alphabetical.paginate(page: params[:page]).per_page(15)
    @inactive_customers = Customer.inactive.alphabetical.paginate(page: params[:page]).per_page(15)
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)
    @user = User.new(user_params)
    @user.role = "customer"
    if !@user.save
      @customer.valid?
      render action: 'new'
    else
      @customer.user_id = @user.id
      if @customer.save
        flash[:notice] = "#{@customer.proper_name} was added to the system."
        session[:user_id] = @customer.user_id
        create_cart
        redirect_to customer_path(@customer)
      else
        render action: 'new'
      end      
    end
  end

  def show
    @previous_orders = @customer.orders.chronological.to_a
    @addresses = @customer.addresses.by_recipient.to_a
  end

  def edit
  end

  def update
    respond_to do |format|
      if @customer.update_attributes(customer_params)
        format.html { redirect_to(@customer, :notice => "Successfully updated #{@customer.proper_name}.") }
        format.json { respond_with_bip(@customer) }
      else
        format.html { render :action => "edit" }
        format.json { respond_with_bip(@customer) }
      end
    end
  end

  private
  def set_customer
    @customer = Customer.find(params[:id])
  end

  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :email, :phone, :active, :username, :password, :password_confirmation)
  end

  def user_params
    params.require(:customer).permit(:active, :username, :password, :password_confirmation)
  end

end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_active_customers.html.erb
<% if @active_customers.empty? %>
  <h4>No active customers at this time.</h4>
<% else %>
  <%= render :partial => "partials/title_with_search", locals: {title: "Active Customers in GPBO"} %>
  <table class="striped highlight">
    <thead>
      <th>Name</th>
      <th>Phone</th>
      <th>Email</th>
    </thead>
    <% for customer in @active_customers %>
      <tr>
        <td><%= link_to "#{customer.last_name}, #{customer.first_name}", customer_path(customer) %></td>
        <td><%= number_to_phone customer.phone %></td>
        <td><%= mail_to customer.email, customer.email, encode: "javascript" %></td>
        </td>
      </tr>
    <% end %>
  </table>
  <br />
  <%= will_paginate @active_customers, previous_label: "Previous&nbsp;", next_label: "&nbsp;Next" %>
<% end %>
<p>&nbsp;</p>

<p><strong>
<%= link_to "Add a New Customer", new_customer_path, class: 'waves-effect waves-light btn' %> 
</strong></p>

app/views/customers/_customer_data.html.erb
<div class="card">
  <div class="card-content">
    <h5><%= best_in_place @customer, :first_name, as: :input %> 
        <%= best_in_place @customer, :last_name, as: :input %></h5>
    <p>A GPBO customer since <%= @customer.created_at.year %></p><br />

    <b>Phone:&nbsp;&nbsp;</b><br>
      <%= best_in_place @customer, :phone, as: :input, display_with: :number_to_phone %><br /><br />

    <b>Email:&nbsp;&nbsp;</b><br>
      <%= best_in_place @customer, :email, as: :input %><br /><br />

    <b>Addresses on file:&nbsp;&nbsp;</b><br>
    <% if @customer.addresses.empty? %>
      <%= "None" %>
    <% else %>
      <table class="striped highlight">
        <thead>
          <th>Address</th>
          <th>Recipient</th>
        </thead>
        <% for address in @customer.addresses %>
          <tr>
            <td><%= link_to (address.street_1 + " " + address.city + ", " + address.state + " " + address.zip), address_path(address) %></td>
            <td><%= address.recipient %></td>
          </tr>
        <% end %>
      </table><br />
    <% end %>

    <b>Order History:&nbsp;&nbsp;</b><br>
    <% if @customer.addresses.empty? %>
      <%= "None" %>
    <% else %>
      <table class="striped highlight">
        <thead>
          <th>Date</th>
          <th>Amount</th>
        </thead>
        <% for order in @customer.orders %>
          <tr>
            <td><%= link_to order.date.strftime("%m/%d/%y"), order_path(order) %></td>
            <td><%= number_to_currency(order.grand_total) %></td>
          </tr>
        <% end %>
      </table><br />
    <% end %>

    <b>Active: </b>
      <%= @customer.active ? "Yes" : "No" %>
      <br>
  </div>
</div>

app/views/customers/_customer_fields.html.erb
<%= f.input :first_name, label_html: { class: 'active' } %>
<%= f.input :last_name, label_html: { class: 'active' } %>
<%= f.input :phone, label_html: { class: 'active' } %>
<%= f.input :email, label_html: { class: 'active' } %>
<%= f.input :active %>

app/views/customers/_form.html.erb
<div class="card">    
  <div class="card-content">
    <%= simple_form_for(@customer) do |f| %>
      <%= f.error_notification %>
      <div class="row">
        <div class="form-inputs">
          <%= f.input :first_name, label_html: { class: 'active' } %>
          <%= f.input :last_name, label_html: { class: 'active' } %>
          <%= f.input :phone, label_html: { class: 'active' } %>
          <%= f.input :email, label_html: { class: 'active' } %>
          <%= f.input :active %>
      </div>
    </div>
  </div>
</div>
  <div class="row">
    <div class="col s12">
      <%= render :partial => "user_fields", locals: {f: f} %>
    </div>
  </div>
  <div class="row">
    <div class="form-actions col s7">
      <%= f.button :submit %>
    </div>
  </div>
<% end %>

app/views/customers/_inactive_customers.html.erb
<br />
<% unless @inactive_customers.empty? %>
  <div class="card yellow lighten-4">
    <div class="card-content">
      <span class="card-title">Inactive Customers</span>
      <ul>
        <% for customer in @inactive_customers %>
          <li><%= link_to customer.name, customer_path(customer) %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/customers/_user_fields.html.erb
<%= f.input :username, label_html: { class: 'active' } %>
<%= f.input :password, label_html: { class: 'active' } %>
<%= f.input :password_confirmation, label_html: { class: 'active' } %>
<%= f.input :greeting, label_html: { class: 'active' } %>

app/views/customers/create.html.erb
<h1>Customers#create</h1>
<p>Find me in app/views/customers/create.html.erb</p>

app/views/customers/edit.html.erb
<h1>Customers#edit</h1>
<p>Find me in app/views/customers/edit.html.erb</p>

app/views/customers/index.html.erb
<%= render partial: "partials/structure1", locals: {model_name: "customer", 
                                                       primary: "active_customers", 
                                                       secondary: nil,
                                                       sidebar: "inactive_customers"} %>

app/views/customers/new.html.erb
<%= render partial: "partials/form2_structure", locals: {object: @customer, 
                                                        type_of_form: "New Customer",
                                                        fields1: "customer_fields",
                                                        section_2: "User Account",
                                                        fields2: "user_fields"} %>

app/views/customers/show.html.erb
<%= render partial: "partials/structure2", locals: { model_name: "customer", 
                                                         object: @customer,
                                                         primary: "customer_data", 
                                                         secondary: nil,
                                                         sidebar: nil } %>

app/views/customers/update.html.erb
<h1>Customers#update</h1>
<p>Find me in app/views/customers/update.html.erb</p>