config/routes.rb
Rails.application.routes.draw do
  # API routing
  scope module: 'api', defaults: {format: 'json'} do
    namespace :v1 do
      # Only need two routes for the API
      get 'orders', to: 'orders#index'
      get 'customers/:id', to: 'customers#show'
    end
  end

  # Semi-static page routes
  get 'home', to: 'home#index', as: :home
  get 'home/about', to: 'home#about', as: :about
  get 'home/contact', to: 'home#contact', as: :contact
  get 'home/privacy', to: 'home#privacy', as: :privacy
  # get 'home/search', to: 'home#search', as: :search
  get 'search', to: 'search#search', as: :search

  # Authentication routes
  get 'login', to: 'sessions#new', as: :login
  get 'logout', to: 'sessions#destroy', as: :logout
  
  resources :sessions, :only => [:new, :create, :destroy]
  resources :customers, :except => [:destroy]
  resources :addresses
  resources :categories, :except => [:show, :destroy]
  resources :items
  resources :orders
  resources :users, :except => [:show, :destroy]

  patch 'items/:id/toggle_active', to: 'items#toggle_active', as: :toggle_active
  patch 'items/:id/toggle_feature', to: 'items#toggle_feature', as: :toggle_feature
  get 'place_order', to: 'orders#create', as: :place_order

  get 'item_prices/new', to: 'item_prices#new', as: :new_item_price
  post 'item_prices/create', to: 'item_prices#create', as: :item_prices

  # URL, Method, Path
  get 'cart/view_cart', to: 'cart#show', as: :view_cart
  get 'cart/:id/add_item', to: 'cart#add_item', as: :add_item
  get 'cart/:id/remove_item', to: 'cart#remove_item', as: :remove_item
  get 'cart/empty_cart', to: 'cart#empty_cart', as: :empty_cart
  get 'cart/checkout', to: 'cart#checkout', as: :checkout

  root 'home#index'
end

app/models/item.rb
class Item < ApplicationRecord
  # Modules to help with some functionality
  include AppHelpers::Validations
  include AppHelpers::Activeable::InstanceMethods
  extend AppHelpers::Activeable::ClassMethods
  
  # Relationships
  belongs_to :category
  has_many :item_prices
  has_many :order_items
  has_many :orders, through: :order_items

  # Scopes
  scope :alphabetical, -> { order(:name) }
  scope :featured,     -> { where(is_featured: true) }
  scope :for_category, ->(category) { where(category_id: category.id) }
  scope :to_reorder,   -> { where('items.reorder_level >= items.inventory_level') }
  scope :search,       ->(term) { where('name LIKE ? OR description LIKE ?', "%#{term}%", "%#{term}%") }


  # Validations
  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates_numericality_of :inventory_level, only_integer: true, greater_than_or_equal_to: 0
  validates_numericality_of :reorder_level, only_integer: true, greater_than_or_equal_to: 0
  validates_numericality_of :weight, greater_than: 0
  validate :category_is_active_in_the_system, on: :create

  # Other methods
  def current_retail_price
    curr = self.item_prices.current.first
    if curr.nil?
      return nil
    else
      return curr.price
    end
  end

  def retail_price_on_date(date)
    data = self.item_prices.for_date(date).first
    if data.nil?
      return nil
    else
      return data.price
    end
  end

  # Callbacks
  before_destroy do
    check_if_item_part_of_any_order
    if errors.present?
      @destroyable = false
      throw(:abort)
    end
  end

  private
  def category_is_active_in_the_system
    is_active_in_system(:category)
  end

  def check_if_item_part_of_any_order
    unless self.order_items.empty?
      errors.add(:base, "This item has already been part of an order and therefore cannot be deleted.")
    end
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :update, :edit, :destroy, :toggle_active, :toggle_feature]
  before_action :check_login, only: [:show, :update, :edit, :destroy]
  authorize_resource

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @category = Category.new(category_params)
    if !@category.save
      @item.valid?
      render action: 'new'
    else
      @item.category_id = @category.id
      if @item.save
        flash[:notice] = "#{@item.name} was added to the system."
        redirect_to item_path(@item)
      # else
      #   render action: 'new'
      end
    end
  end

  def index
    @categories = Category.alphabetical
    if params[:category].present?
      category = Category.find(params[:category])
      @featured_items = Item.active.featured.for_category(category).alphabetical.paginate(page: params[:page]).per_page(15)
      @other_items = Item.active.for_category(category).alphabetical - Item.featured
    else
      @featured_items = Item.featured.alphabetical.paginate(page: params[:page]).per_page(15)
      @other_items = Item.active.alphabetical - Item.featured
    end
  end

  def show
    @prices = ItemPrice.for_item(@item)
    @similar_items = Item.for_category(@item.category)
  end

  def update
    if @item.update_attributes(item_params)
      flash[:notice] = "Successfully updated #{@item.name}."
      redirect_to @item
    else
      render action: 'edit'
    end
  end

  def edit
  end

  def destroy
    @item = Item.find(params[:id])
    if @item.order_items != nil
      @item.destroy
      flash[:notice] = "Successfully removed this treatment."
      redirect_to @item
    end
  end

  def toggle_active
    if @item.active == true
      @item.update_attribute(:active, false)
      flash[:notice] = "#{@item.name} was made inactive"
    else
      @item.update_attribute(:active, true)
      flash[:notice] = "#{@item.name} was made active"
    end
    redirect_to @item
  end

  def toggle_feature
    if @item.is_featured
      @item.update_attribute(:is_featured, false)
      flash[:notice] = "#{@item.name} is no longer featured"
    else
      @item.update_attribute(:is_featured, true)
      flash[:notice] = "#{@item.name} is now featured"
    end
    redirect_to @item
  end

  private
  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, :description, :association, :color, :inventory_level, :reorder_level, :weight, :is_featured, :active)
  end

  def category_params
    params.require(:item).permit(:name, :active)
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<div class="card">    
  <div class="card-content">
    <%= simple_form_for(@item) do |f| %>
      <%= f.error_notification %>
      <div class="row">
        <div class="form-inputs">
          <%= f.input :name, label_html: { class: 'active' } %>
          <%= f.input :category_id, collection: Category.alphabetical.active.to_a%>
          <%= f.input :description, label_html: { class: 'active' } %>
          <%= f.input :color, label_html: { class: 'active' } %>
          <%= f.input :inventory_level, label_html: { class: 'active' } %>
          <%= f.input :reorder_level, label_html: { class: 'active' } %>
          <%= f.input :weight, label_html: { class: 'active' } %>
          <%= f.input :active %>
          <%= f.input :is_featured %>
      </div>
    </div>
  </div>
</div>
  <div class="row">
    <div class="form-actions col s8">
      <%= f.button :submit %>
    </div>
  </div>
<% end %>

app/views/items/_item_data.html.erb
<div class="card">
  <div class="card-content">
    <h5>Information for <%= @item.name %></h5><br />

    <b>Description: </b>
      <%= @item.description %><br /><br />

    <b>Color: </b>
      <%= @item.color %><br /><br />

    <b>Weight: </b>
      <%= @item.weight %> lbs<br /><br />

    <b>Current Price: </b>
      <%= number_to_currency(@item.current_retail_price) unless @item.current_retail_price == nil %><br /><br />

    <% if logged_in? && current_user.role?(:admin) %>
      <b>Inventory Level: </b>
        <%= @item.inventory_level %><br /><br />
      
      <b>Reorder Level: </b>
        <%= @item.reorder_level %><br /><br />
    <% end %>

    <b>Currently offered? </b>
      <%= @item.active ? "Yes" : "No" %><br><br><br>
  </div>
</div>

app/views/items/_item_fields.html.erb
<%= f.input :name, label_html: { class: 'active' } %>
<%= f.input :category_id, collection: Category.alphabetical.active.to_a %>
<%= f.input :description, label_html: { class: 'active' } %>
<%= f.input :color, label_html: { class: 'active' }, include_blank: true %>
<%= f.input :inventory_level, label_html: { class: 'active' } %>
<%= f.input :reorder_level, label_html: { class: 'active' } %>
<%= f.input :weight, label_html: { class: 'active' } %>
<%= f.input :active %>
<%= f.input :is_featured %>

app/views/items/_item_search.html.erb
<% unless @items.empty? %>
  <p><em><strong>Items matching term '<%= @query %>'</strong></em></p>
  <ul>
    <% for item in @items do %>
      <li><%= link_to item.name, item_path(item) %></li>
    <% end %>
  </ul>
  <p class="supertiny">&nbsp;</p>
<% end %>

app/views/items/_items_list.html.erb
<h4>Featured Items at GPBO</h4>

<% if @featured_items.empty? %>
  <h5>There are no featured items in that category at this time.</h5><br /><br /><br />
<% else %>
  <table class="striped highlight">
    <thead>
      <th>Name</th>
      <th>Price</th>
      <% if logged_in? && current_user.role?(:admin) %>
        <th>Inventory</th>
      <% end %>
    </thead>
    
    <% for item in @featured_items %>
      <tr>
        <td><%= link_to item.name, item_path(item) %></td>
        <td class="align_center"><%= item.item_prices.current.first.nil? ? 'N/A' : number_to_currency(item.item_prices.current.first.price) %></td>
        <% if logged_in? && current_user.role?(:admin) %>
          <td>&nbsp;&nbsp;&nbsp;&nbsp;<%= item.inventory_level %></td>
        <%# <% else %>
          <%# <td class="align_center"><%= link_to "Add to Cart", add_item_path(item) %>
          <%# <td class="align_center"> %>
          <%# <%= link_to add_item_path(item) do %>
              <%# &nbsp;&nbsp; %>
              <%# <i class="material-icons">shopping_cart</i> %>
          <%# <% end %>
          <%# </td> %>
        <% end %>
      </tr>
    <% end %>
  </table>
  <br />
  <%= will_paginate @featured_items, previous_label: "Previous&nbsp;", next_label: "&nbsp;Next" %>
  <p>&nbsp;</p>
<% end %>

<h4>Other Items at GPBO</h4>

<% if @other_items.empty? %>
  <h5>There are no other items in this category at this time.</h5><br /><br /><br />
<% else %>
  <table class="striped highlight">
    <thead>
      <th>Name</th>
      <th>Price</th>
      <% if logged_in? && current_user.role?(:admin) %>
          <th>Inventory</th>
      <% end %>
    </thead>
    <% for item in @other_items %>
      <tr>
        <td><%= link_to item.name, item_path(item) %></td>
        <td class="align_center"><%= item.item_prices.current.first.nil? ? 'N/A' : number_to_currency(item.item_prices.current.first.price) %></td>
        <% if logged_in? && current_user.role?(:admin) %>
          <td>&nbsp;&nbsp;&nbsp;&nbsp;<%= item.inventory_level %></td>
          <td class="align_center">
        <%# <% else %>
        <%# <td class="align_center><%= link_to "Add to Cart", add_item_path(item) %>
          <%# <td class="align_center"> %>
          <%# <%= link_to add_item_path(item) do %>
              <%# &nbsp;&nbsp; %>
              <%# <i class="material-icons">shopping_cart</i> %>
          <%# <% end %>
          <%# </td> %>
        <% end %>
      </tr>
    <% end %>
  </table>
<% end %>

<%= render :partial => "partials/add_new_object", locals: {model_name: 'item'} %>

app/views/items/_price_history.html.erb
<% unless @prices.empty? %>
  <div class="card">
    <div class="card-content">
      <span class="card-title">Price History</span>
      <table class="striped highlight">
      <thead>
        <th>Date</th>
        <th class="align_right">Price</th>
      </thead>
        <% for price in @prices %>
          <tr>
            <td><%= price.start_date.strftime("%b %d, %Y") %></td>
            <td class="align_right"><%= number_to_currency(price.price) %></td>
          </tr>
        <% end %>
    </table>
    </div>
    <% if can? :new, ItemPrice %>
      <div class="card-action">
        <%= link_to "Add a New Price", new_item_price_path(item_id: @item.id) %>
      </div>
    <% end %>
  </div>
<% else %>
  <% if can? :new, ItemPrice %>
    <div class="card grey lighten-3">
      <div class="card-action">
        <%= link_to "Add a New Price", new_item_price_path(item_id: @item.id) %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/items/_similar_items_list.html.erb
<br />
<% unless @similar_items.empty? %>
  <div class="card yellow lighten-4">
    <div class="card-content">
      <span class="card-title">Similar Items</span>
      <ul>
        <% for item in @similar_items %>
          <li><%= link_to item.name, items_path(item) %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/items/destroy.html.erb
<h1>Items#destroy</h1>
<p>Find me in app/views/items/destroy.html.erb</p>

app/views/items/edit.html.erb
<%= render partial: "partials/form_structure", locals: {object: @item, 
                                                        type_of_form: "Edit Item",
                                                        fields: "item_fields" } %>

app/views/items/index.html.erb
<%= render partial: "partials/structure1", locals: {model_name: "item", 
                                                       primary: "items_list", 
                                                       secondary: nil,
                                                       sidebar: "category_list" } %>

app/views/items/new.html.erb
<%= render partial: "partials/form_structure", locals: { object: @item, 
                                                         type_of_form: "New Item",
                                                         fields: "item_fields" } %>

app/views/items/show.html.erb
<% if logged_in? && current_user.role?(:admin) %>
    <%= render partial: "partials/structure2", locals: { model_name: "item", 
                                                         object: @item,
                                                         primary: "item_data", 
                                                         secondary: nil,
                                                         sidebar: "price_history" } %>
<% else %>
    <%= render partial: "partials/structure2", locals: { model_name: "item", 
                                                         object: @item,
                                                         primary: "item_data", 
                                                         secondary: nil,
                                                         sidebar: "similar_items_list" } %>
<% end %>

app/views/items/update.html.erb
<h1>Items#update</h1>
<p>Find me in app/views/items/update.html.erb</p>